config/routes.rb
Rails.application.routes.draw do
  root to: "flats#home"

  resources :flats do
    resources :bookings, only: [:create, :new]
  end
  devise_for :users
  resources :bookings, only: :index

  get "/action", to: "flats#action"
  get "/booking/confirm", to: "bookings#bookingconfirm"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flat
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
  validates :street_address, presence: true
  # validates :description, presence: true
  # validates :capacity, presence: true

  geocoded_by :street_address
  after_validation :geocode, if:
  :will_save_change_to_street_address?

  # dont want to delete the below in case it breaks something but we may not need it pls check in merge
  belongs_to :user

  include PgSearch::Model
  pg_search_scope :search_by_street_address_and_description,
    against: [ :street_address, :description ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :flats
  has_many :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show_one
    @bookings = Booking.where(user: current_user)
  end

  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
    @flat = Flat.find(params[:flat_id])
  end

  def create
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.new(booking_params)
    @booking.flat = @flat
    @booking.user = current_user
    if @booking.save

      redirect_to flats_path

    else
      render "bookings/new", status: :unprocessable_entity
    end
  end
 def bookingconfirm

 end
  def show
    @booking = User.find(params[:user_id]).bookings
  end

  private

  def booking_params
    params.require(:booking).permit(:startdate, :enddate)

  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]


  def home
  end

  def index
    # @flats = Flat.all
    if params[:query].present?
      @flats = Flat.search_by_street_address_and_description(params[:query])
    else
      @flats = Flat.all
    end
    @markers = @flats.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude
      }
    end
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user
    if @flat.save!
      redirect_to flat_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @flat = Flat.find(params[:id])
    @booking = Booking.new
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    flat = Flat.find(params[:id])
    flat.update(flat_params)
    redirect_to flat_path(flat)
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to root_path
  end

  def update
  end

  private


  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :street_address, :description, :capacity, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/bookingconfirm.html.erb
<p>Booking complete</p>
<%= link_to "back to home", root_path %>

<div class="container">


<h3 class="border-bottom">Thank you for booking with us!</h3>

  <%# <div class="row">
    <h3>Confirm & Pay</h3>
  </div>

  <div class="row">
    <h4>Your trip</h4>
    <p>Dates</p>
    <p></p>
  </div> %>

  <%= link_to "back to home", root_path %>
</div>

app/views/bookings/index.html.erb
<ul>
  <li>FLAT NAME          STARTDATE        END DATE</li>
  <p>--------------------------------------------------</p>
  <% @bookings.each do |booking| %>
  <li> <%= booking.flat.name %><%= booking.startdate %><%= booking.enddate %></li>
  <%= end %>
</ul>

app/views/bookings/new.html.erb
<h1>Booking for <%= @flat.name%> </h1>
    <%= simple_form_for [@flat, @booking] do |f| %>
  <%= f.input :startdate, as: :date %>
  <%= f.input :enddate, as: :date %>

  <%= f.submit "Confirm Booking", class: "btn btn-primary" %>

  <% end %>

app/views/bookings/show_one.html.erb
<% @bookings.each do |b| %>
  <h2>flat: <%= b.flat.name %></h2>

  <p>start date: <%= b.startdate %></p>
  <p>end date: <%= b.enddate %></p>
  <p></p>

<% end %>

app/views/flats/_form.htm.erb
<%= f.input :street_address,
  input_html: {data: {address_autocomplete_target: "address"}},
  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
%>

app/views/flats/_form.html.erb
<%= f.input :street_address,
  input_html: {data: {address_autocomplete_target: "address"}},
  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
%>

app/views/flats/edit.html.erb
<h1>Edit flat</h1>
<%= simple_form_for(@flat) do |f| %>
    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :street_address %>
      <%= f.input :description %>
      <%= f.input :capacity, collection: 1..10 %>
      <%= f.input :photo, as: :file %>
      <%= f.button :submit %>
    </div>
<% end %>

app/views/flats/home.html.erb
<%#
  <body class="p-3 m-0 border-0 bd-example"> %>

<div class="container">

<%# THIS IS THE TITLE AND A BIT ABOUT AND A DISCOVER MORE BUTTON %>
  <div class="flex-box">
    <div class="row">
      <h1 class="title">FLENTAL<h1>
    </div>

    <div class="row">
    <h3>Rent a flat or rent your flat in London!</h3>
    </div>

    <div class="row">
      <div class="col-sm-6 host-text">
        <p>Have you ever wondered what your flat does when you go back home for the weekend?
        <br>Use Flental to make money from renting your flat while you're away! </p>
      </div>

      <div class="col-sm-6 rent-text">
        <p>Have you ever visited London and wanted to stay in a fitted and kitted out just how you like it?
          <br>While you're visiting London for the weekend why not stay in a swanky space!
        </p>
      </div>
    </div>

    <div class="row">
      <h3>Flental brings together trusted hosts and hostees </h3>
    </div>
    <br>
    <%= link_to "Discover", flats_path, class:"btn-flat"%>
  </div>
    <br>
    <br>
  <%# THIS IS THE CAROSEL OF IMAGES %>

  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item">
        <img src="https://images.unsplash.com/photo-1661916123448-116815d2f40b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1288&q=80" class="d-block w-100" style="height: 700px" alt="...">
      </div>
      <div class="carousel-item active">
        <img src="https://images.unsplash.com/photo-1661916123448-116815d2f40b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1288&q=80" class="d-block w-100" style="height: 700px" alt="...">
      </div>
      <div class="carousel-item">
        <img src="https://images.unsplash.com/photo-1451153378752-16ef2b36ad05?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2067&q=80" class="d-blockw-100" style="height: 700px" alt="flats">
      </div>
    </div>

    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

app/views/flats/index.html.erb
<%# THIS PAGE IS THE HOME PAGE, IT SHOWS ALL THE FLATS
IT HAS A SEARCH FUNCTION
A BACKGROUND IMAGE WITH TITLE
A BECOME A HOST BUTTON
IT IS SHOWING ALL THE FLATS
AND IT HAS A MAP FUNCTION DISPLAYING THE FLATS %>


<%= form_with url: flats_path, method: :get, class: "d-flex my-3 mx-2" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a flat"
  %>
  <%= submit_tag "Search", class: "btn-flat" %>
<% end %>

<%# This is the banner outside of the container %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1661796428215-04fc2830aae6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1588&q=80.jgp);">
  <h1 id="title">FLENTAL</h1>
  <p>Bringing together trusted hosts and hostees</p>
  <a class="btn-flat" <%= link_to "Become a host!", new_flat_path%>>
</div>


<div class="container">
  <div class="cards">
    <% @flats.each do |flat| %>
    <%= link_to flat_path(flat), class: "text-decoration-none" do %>
      <div class="card">
        <% if flat.photo.attached? %>
        <%= cl_image_tag flat.photo.key, width: 400, height: 300, crop: :fill, class: "card-img" %>
        <% else %>
        <% end %>
          <div class="card-infos">
            <div>
              <h2><%= flat.name %></h2>
              <p class="address"><%= flat.street_address %></p>
              <p><%= flat.description %></p>
            </div>
            <h2 class="card-pricing">£100</h2>
          </div>
      </div>
    <% end %>
    <% end %>
  </div>
</div>

<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/flats/new.html.erb
<div class="container">

  <div class="host-form">
    <h1>BECOME A HOST...</h1>
    <%= simple_form_for @flat do |f| %>
    <div class="form-inputs">
      <%= f.input :name, placeholder: "e.g The Bachelor Pad" %>
      <%= f.input :street_address %>
      <%= f.input :description, placeholder: "Pink, fluffy and secluded" %>
      <%= f.input :capacity, collection: 1..10 %>
      <%= f.input :price, placeholder: "£5,000,000,000" %>
      <%= f.input :photo, as: :file %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, "Start hosting", class: "btn-flat" %>
    </div>
    <% end %>
  </div>
</div>

app/views/flats/show.html.erb
<%# THIS PAGE SHOWS THE SELECTED FLAT
YOU CAN EDIT DELETE BOOK OR GO BACK  %>

<div class="container">
  <h1><%= @flat.name %></h1>

    <div class="flex-box">
      <div class="row image">
      <%= cl_image_tag @flat.photo.key, height: 500, width: 400, crop: :fill , class: "img"%>
      </div>

      <div class="row">

        <h3><%= @flat.description %></h3>
      </div>
      <div class="row">
        <div class="col-4 btn btn-flat">
          <%= link_to "Book Now", new_flat_booking_path(@flat)  %>
        </div>
        <div class="col-4 btn btn-light">
          <%= simple_form_for @flat, method: :delete do |f| %>
          <%= f.button :submit, 'Delete', class: "btn-light" %>
          <% end %>
        </div>
        <div class="col-4 btn btn-light">
          <%= link_to "Edit", edit_flat_path, class: "btn btn-light" %>
        </div>
      </div>
    </div>
</div>

app/views/flats/update.html.erb
<h1>Flat updated</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flental</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
    <link href="https://getbootstrap.com/docs/5.2/assets/css/docs.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>

    <!-- JavaScript Bundle with Popper -->
    <!-- JavaScript Bundle with Popper -->

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

      <%= yield %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <i class="fas fa-heart"></i> Flats at Flentel
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">

    <%= link_to flats_path, class: "navbar-brand" do %>


        <%= image_tag "https://images.unsplash.com/photo-1547387557-21339915455f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2835&q=80" %>
      <% end %>



    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", flats_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "About", flats_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact Us", flats_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Account", flats_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://images.unsplash.com/photo-1640951613773-54706e06851d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1480&q=80", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">

              <%# <%= link_to "Update a Flat", "#", class: "dropdown-item" %>
              <%= link_to "Log out", flats_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>